config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get  '/policy', to: 'static_pages#policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/likes/:id', to: 'likes#show'
  post '/likes/:id', to: 'likes#create'
  delete '/likes/:id/destroy', to: 'likes#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:index, :new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments,            only: [:create, :destroy]
  resources :alerts,              only: [:show, :destroy]
  
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :picture, PictureUploader
  has_many :microposts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :alerts, dependent: :destroy
  
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy                                
                                  
  has_many :following, through: :active_relationships, source: :followed 
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token
  validates :name,  presence: true, length: { maximum: 50 }
  validates :nickname, presence: true, length: { maximum: 50 },
                         uniqueness: { case_sensitive: false }
  validates :introduction, length: { maximum: 140 }                       
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true
  
  # 渡された文字列のハッシュ値を返す。
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end
  
  # ユーザーをフォローする
  def follow(other_user)
    self.active_relationships.create(followed_id: other_user.id)
  end                    

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :show, :update, :destroy, :following, :followers]
  before_action :correct_user,   only: [:edit, :update, :destroy]
  
  def index
    @users = User.paginate(page: params[:page])
  end 
  
  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end
  
  def new
    @user = User.new 
  end
  
  def create
    @user = User.new(user_params)    
    if @user.save
      log_in @user
      flash[:success] = "アカウントが作成されました！"
      redirect_to @user 
    else
      render 'new'
    end 
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "アカウント情報を変更しました。"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "アカウントを削除しました。"
    redirect_to root_url
  end
  
  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :nickname, :introduction, :picture, :password,
                                   :password_confirmation)
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },remote: true) do |f| %>
  <%= f.submit "フォローを解除する", class: "btn btn-primary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <section class="user_info">
    <% if user.picture? %>
      <div class = "user_icon"><%= image_tag user.picture.thumb50.url %></div>
    <% else %>
      <div class = "user_icon"><img src = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png" width = 50, height = 50></div>
    <% end %>
  <div class = "userspage_name"><%= link_to user.name, user %></div>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :nickname, "ニックネーム" %>
      <%= f.text_field :nickname, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認用）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      <div class="field">
        <%= f.label :introduction, "自己紹介" %>
    　　<%= f.text_area :introduction, placeholder: "自己紹介文を書こう！" %>
  　　</div>
  　　
  　　<span class="picture">
       <%= f.file_field :picture, accept: 'image/jpeg,image/png' %>
      </span>

      <%= f.submit "プロフィールを変更する", class: "btn btn-primary" %>
    <% end %>
    
    <% if current_user?(@user) %>
      <%= link_to "アカウントを削除する", @user, method: :delete,
                                    data: { confirm: "本当に削除してよろしいですか?" } %>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name, "名前" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :nickname, "ニックネーム" %>
      <%= f.text_field :nickname, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワード（確認用）" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      
      
      <div class="field">
        <%= f.label :introduction, "自己紹介" %>
    　　<%= f.text_area :introduction, placeholder: "自己紹介文を書こう！" %>
  　　</div>
      

      <%= f.submit "アカウントを作成する", class: "btn btn-primary" %>
    <% end %>
    <div class = "policy"><%= link_to "利用規約", policy_path %></div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <% if @user.picture? %>
        <div class = "user_icon"><%= image_tag @user.picture.thumb100.url %></div>
      <% else %>
        <div class = "user_icon"><img src = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png" width = 100, height = 100></div>
      <% end %>
      <h1><%= @user.name %></h1>
      <h1><%= @user.nickname %></h1>
      <p>【自己紹介】</p>
      <p><%= @user.introduction %></p>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>投稿 (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
  <div class="modal fade" id="user-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true"></div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  
  <div class="col-md-8">
    <h1><%= @title %></h1>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>