config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get  '/policy', to: 'static_pages#policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/likes/:id', to: 'likes#show'
  post '/likes/:id', to: 'likes#create'
  delete '/likes/:id/destroy', to: 'likes#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:index, :new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments,            only: [:create, :destroy]
  resources :alerts,              only: [:show, :destroy]
  
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <span class="picture">
    <%= f.file_field :picture, accept: 'image/jpeg,image/png' %>
  </span>
  <%= f.submit "投稿する", class: "btn btn-primary" %>
<% end %>

app/views/shared/_search_form.html.erb
<%= search_form_for @q do |f| %>
  <%= f.label :picture_cont, 'Picture Search' %>
  <div class="input-group">
    <%= f.text_field :picture_cont, placeholder: "Enter keywords...",
                      class: 'form-control' %>
    <span class="input-group-btn">
     <%= f.submit '検索', class: "btn btn-primary" %>
    </span>
  </div>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    人をフォロー中
  </a>
  <a href="<%= followers_user_path(@user) %>">
    フォロワー
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    人
  </a>
</div>

app/views/shared/_user_info.html.erb
<% if current_user.picture? %>
  <div class = "user_icon"><%= image_tag current_user.picture.thumb100.url %></div>
<% else %>
  <div class = "user_icon"><img src = "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460__480.png" width = 100, height = 100></div>
<% end %>
<div class = "users_name">
  <h1><%= current_user.name %></h1>
  <h1><%= current_user.nickname %></h1>
</div>
<p>【自己紹介】</p>
<p><%= current_user.introduction %></p>