config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get  '/policy', to: 'static_pages#policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/likes/:id', to: 'likes#show'
  post '/likes/:id', to: 'likes#create'
  delete '/likes/:id/destroy', to: 'likes#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:index, :new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments,            only: [:create, :destroy]
  resources :alerts,              only: [:show, :destroy]
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :picture, presence: true 
  validate  :picture_size
  
  private

    # アップロードされた画像のサイズをバリデーションする
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "5MB以内の画像にしてください。")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:index, :new, :create, :destroy]
  before_action :correct_user,   only: :destroy
  
  def new
    @micropost = current_user.microposts.build(micropost_params)
  end
  
  def index
    @q = Micropost.all.ransack(params[:q])
    @microposts = @q.result(distinct: true)
  end
  
  def show
   @user = current_user
   @micropost = Micropost.find(params[:id])
   @comment = current_user.comments.build
   @comments = Comment.where(micropost_id: @micropost.id)
  end 
  
  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "投稿に成功しました!"
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end
  
  def destroy
    @micropost.destroy
    flash[:success] = "投稿を削除しました。"
    redirect_to request.referrer || root_url
  end
  
  private

    def micropost_params
      params.fetch(:micropost, {}).permit(:picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end 
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_comment.html.erb
<li>
  <%= comment.content %>    
</li>

app/views/microposts/_micropost.html.erb
<div class = "pictures"> 
 <ul>
   <li>
    <div class = "picture">
     <%= link_to image_tag("#{micropost.picture.url}"), micropost_path(micropost), remote: true %>
     <div> 
       <%if Like.find_by(user_id: current_user.id, micropost_id: micropost.id) %>
         <%=link_to("/likes/#{micropost.id}/destroy",{method: "delete"}) do %>
           <span class="fa fa-heart like-btn-unlike"></span>
         <% end %>
       <%else%>
        <%=link_to("/likes/#{micropost.id}",{method: "post"}) do %>
          <span class="fa fa-heart like-btn"></span>
        <% end %>
       <%end%>
       <%= Like.where(micropost_id: micropost.id).count %>
       <% @user = User.find_by(id: micropost.user_id) %>
       <% if current_user?(@user) %>
         <%= link_to micropost, method: :delete,
                                    data: { confirm: "本当に削除してよろしいですか?" } do %>
           <span class="fa fa-trash" id = "trash"></span>
         <% end %>   
       <% end %>
     </div> 
    </div>
   </li>
 </ul>
</div> 

app/views/microposts/_show.html.erb
<div class = 'modal-open'>
  <div class = 'modal_picture'><%= image_tag("#{@micropost.picture.thumb300.url}") %> </div>
  
  <%= form_for(@comment) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="field">
      <%= hidden_field_tag :micropost_id, @micropost.id.to_i %>
      <div class = 'comment_field'> <%= f.text_area :content, placeholder: "コメントしてみよう！" %> </div>
    </div>
    <div class = 'comment_button'><%= f.submit "コメントする", class: "btn btn-primary" %> </div>
  <% end %>
  
  <h3>コメント</h3>
  <ul class="users">
    <% @comments.each do |comment| %>
     <% @user = User.find_by(id: comment.user_id) %>
     <li>
      <%= link_to "#{@user.name}", @user %> |
      <%= comment.content %>
      <% if comment.user_id == current_user.id %>
    　　<%= link_to '削除', comment, method: :delete,
                                    data: { confirm: "本当に削除してよろしいですか?" } %>
  　　<% end %>
     </li>  
    <% end %>
  </ul>
</div>


  

app/views/microposts/index.html.erb
<div class = "container">
  <div class="search_form">
    <%= render 'shared/search_form' %>
  </div>
  <ol class="microposts">
    <%= render @microposts %>
  </ol>
</div>

app/views/microposts/new.html.erb
<% provide(:title, "Post") %>
 <section class="micropost_form">
   <%= render 'shared/micropost_form' %>
 </section>

app/views/microposts/show.js.erb
$("#user-modal").html("<%= escape_javascript(render 'show') %>");
$("#user-modal").modal("show");