config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  root 'static_pages#home'
  get  '/policy', to: 'static_pages#policy'
  get '/signup', to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/likes/:id', to: 'likes#show'
  post '/likes/:id', to: 'likes#create'
  delete '/likes/:id/destroy', to: 'likes#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts,          only: [:index, :new, :show, :create, :destroy]
  resources :relationships,       only: [:create, :destroy]
  resources :comments,            only: [:create, :destroy]
  resources :alerts,              only: [:show, :destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <p>Insta app by daiki yokota</p>
  </small>
  <nav>
    <ul>
      <% if logged_in? %>
        <li><%= link_to "投稿する", "/microposts/new" %></li>
      <% end %>  
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="app-title.navbar.navbar-expand-md.navbar-light.bg-light">
  <div class="container">
    <div class="navbar-header">

      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
    <div class = "navbar-brand">
      <%= link_to '/', id: "logo" do %>
        <span class="fa fa-instagram" id = "instagram"></span>| <font face= "cursive">Insta app</font> 
      <% end %>  
    </div>
  </div>
    <nav>
      <ul id="navbar" class="nav navbar-nav navbar-right navbar-collapse collapse">
        <% if logged_in? %>
          <li>
            <%= link_to microposts_path do%>
              <span class= "fa fa-search" id = "search"></span>
            <% end %>
          </li>
          <li>
            <%= link_to alert_path(current_user) do %>
              <span class="fa fa-bell" id = "bell"></span>
            <% end %>     
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <span class="fa fa-user" id = "user_icon"></span> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "マイページ", current_user %></li>
              <li><%= link_to "おすすめユーザー", users_path %></li>
              <li><%= link_to "お気に入り", "/likes/#{current_user.id}" %></li>
              <li><%= link_to "プロフィール設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "新規登録", signup_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= render 'layouts/shim' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>